var gProjs = [
  {
    id: makeId(),
    name: "AriellaGram",
    title: "My own version of Instagram built with Vue",
    description: "This is my first fullstack project.  I used Vue, Node.js and MongoDB.  It is my imitation of Instagram.",
    imgUrl: "img/portfolio/ariellaGram.png",
    link: "https://ariellagram.herokuapp.com/#/login",
    linkToGithub:"https://github.com/Ariellaw/my-insta",
    framework: "Vue",
    labels: ["Vue", "keyboard events"],
    underConstruction: false,
  },
  {
    id: makeId(),
    name: "Forecast",
    title: "World Weather Information Service",
    description: "This is a weather information site build using Angular", 
    imgUrl: "img/portfolio/forecast.PNG",
    link: "https://ariella-forecast-app.herokuapp.com/home",
    linkToGithub:"https://github.com/Ariellaw/Ariella-Wills-25-3-2020",
    framework: "Angular",
    labels: ["Angular"],
    underConstruction: false,
  },
  {
    id: makeId(),
    name: "Palindromer",
    title: "Palindromer",
    description: "This is my first Angular project.  It helps users create palindromes, which are words or sentences that read the same way forwards or backwards.",
    imgUrl: "img/portfolio/palindromer.PNG",
    link: "palindromer",
    linkToGithub:"https://github.com/Ariellaw/palindromer",
    framework: "Angular",
    labels: ["Angular", "keyboard events"],
    underConstruction: true,
  }
];
